#!/usr/bin/env python3
"""Generate the pf_feature.h stub from the real upstream header.

The point is not convenience. `PFFeature` descriptors are positional
aggregate initializers, and upstream's own header warns that adjacent fields
of the same type reorder without a compiler diagnostic — the build stays green
and every feature quietly wires the wrong function to the wrong hook.

So the stub is not hand-written: the two struct blocks are lifted verbatim out
of the vendored core, and feature_screencast.h is compiled against them. If
upstream appends, reorders, or retypes a field, this test stops compiling —
which is the diagnostic the real build cannot give us.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CORE = os.path.join(ROOT, "vendor", "patternflow", "firmware", "patternflow")
OUT = os.path.join(ROOT, "tools", "hosttest", "stub", "features", "pf_feature.h")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("//")
    )


def extract_struct(path, name):
    with open(path, encoding="utf-8") as fh:
        src = strip_comments(fh.read())
    m = re.search(r"\bstruct\s+%s\s*\{" % re.escape(name), src)
    if not m:
        sys.exit("could not find 'struct %s' in %s" % (name, path))
    i = src.index("{", m.start())
    depth = 0
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                body = src[i + 1:j]
                lines = [l.rstrip() for l in body.splitlines() if l.strip()]
                return "struct %s {\n%s\n};\n" % (name, "\n".join(lines))
    sys.exit("unbalanced braces reading 'struct %s'" % name)


def main():
    feature_h = os.path.join(CORE, "features", "pf_feature.h")
    encoders_h = os.path.join(CORE, "src", "core_encoders.h")
    for p in (feature_h, encoders_h):
        if not os.path.exists(p):
            sys.exit(
                "vendor/patternflow is not checked out (%s missing).\n"
                "  git submodule update --init --depth 1" % p
            )

    parts = [
        "// GENERATED by tools/hosttest/gen_stub.py — do not edit.",
        "// The struct bodies below are lifted verbatim from the vendored core so",
        "// that our positional descriptor is checked against upstream's real",
        "// field order. Regenerate after updating the submodule.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        extract_struct(encoders_h, "InputFrame"),
        extract_struct(feature_h, "PFFeatureFrame"),
        extract_struct(feature_h, "PFFeature"),
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(parts))
    print("wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
